---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
- name: npm_install
  image: node:hydrogen
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm ci
  environment:
    NPM_INSTALL_TOKEN:
      from_secret: npm_install_token

- name: test
  image: node:hydrogen
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm test
  environment:
    NPM_INSTALL_TOKEN:
      from_secret: npm_install_token

- name: typings
  image: node:hydrogen
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_INSTALL_TOKEN}" > ~/.npmrc
  - npm run types
  environment:
    NPM_INSTALL_TOKEN:
      from_secret: npm_install_token

- name: release
  image: node:hydrogen
  commands:
  - echo "//registry.npmjs.org/:_authToken=$${NPM_DEPLOY_TOKEN}" > ~/.npmrc
  - echo "unsafe-perm=true" >> ~/.npmrc
  - npm publish
  environment:
    NPM_DEPLOY_TOKEN:
      from_secret: npm_deploy_token
  when:
    event:
    - tag
...
